### ISSUE TITLE
Game slows down when there are many Air Wizards spawned

### ISSUE THREAD

**Issue by Makkkkus** [chrisj42/minicraft-plus-revived#142]
I believe it is because of the particles spawned, and therefore can be "easily" fixed.

**Comment by alice39** [comment]
mmm, I did a attempting to optimize the sparks at [this PR#143](https://github.com/chrisj42/minicraft-plus-revived/pull/143#issue-563321395) because it creates a lot of sparks and then the game checks if one of entities [ sparks are included too ] is in a bound to be hit by spark, I decided to create a spark list apart from entity list in Level, to avoid to loop for those sparks also I kinda reduced how many sparks Air Wizards generate

**Comment by Makkkkus** [comment]
Exellent

**Comment by africalinguist** [comment]
#143 merged, so this can be considered fixed
