### ISSUE TITLE
Why are you publishing the incomplete source code? Do not publish it for that.

### ISSUE THREAD

**Issue by AkousMod** [chrisj42/minicraft-plus-revived#163]
Anyway, Notch made this game in less than 48 hours. And you in more than two years (17.520 hours) have barely been able to move forward... Consider sharing the source code because what you are doing does not make any sense and that is why the game is still so stagnant.

**Comment by TheBigEye** [comment]
sir... the source code is complete, Minicraft plus is an extension of the original Minicraft of Notch (it is not the original minicraft itself, because the code is going to be different), the source code is complete, only that for the years it has There have been changes to improve the game, and I would say that the game advanced a lot in two years, since there is not a very small screen, there are different game modes, worlds can be saved and loaded, etc.

if you want the original source code look here [Source code](https://github.com/skeeto/Minicraft)

**Comment by chrisj42** [comment]
not sure what OP meant originally, perhaps you tried compiling it and it didn't work? This is the full source. There is nothing else. If make sure you have all the required libraries, which should all be in the lib/ folder.
