### ISSUE TITLE
Make localization work in the IDE

### ISSUE THREAD

**Issue by Makkkkus** [chrisj42/minicraft-plus-revived#213]
**Is your feature request related to a problem? Please describe.**
Localization doesn't work when using the IDE.

**Describe the solution you'd like**
Change the system so it supports localization in the IDE.

**Comment by lino-levan** [comment]
What does this mean?

**Comment by Makkkkus** [comment]
Localization doesn't work in the IDE because of some strange reason. Try to enable localization when running this in an IDE.

**Comment by lino-levan** [comment]
I mean according to the code, that's intentional(?)

```java
// e is either null if there are no entries left, or if
// we're running this from an ide (at least for eclipse)
if (e == null) {
  if (reads > 0) break;
  else {
	  return getLanguagesFromDirectoryUsingIDE();
  }
}
```

Apparently the code for reading the localization files was found [here on stackoverflow](https://stackoverflow.com/questions/1429172/how-do-i-list-the-files-inside-a-jar-file/1429275#1429275) and in that thread someone mentions that it doesn't work in the IDE.

Later in that thread some people claim to have found solutions that work both when packaged and in the IDE.

If someone wants to fix `getLanguagesFromDirectory()` in `Localization.java` then this """bug""" is fixed.

**Comment by Makkkkus** [comment]
Thank you
