### ISSUE TITLE
[FEATURE] Be able to add letters or symbols like world seed

### ISSUE THREAD

**Issue by TheBigEye** [chrisj42/minicraft-plus-revived#226]
**Is your feature request related to a problem? Please describe.**
Currently, only numbers can be entered as seed

**Describe the solution you'd like**
The user could enter any set of characters (!"#$%&/(=*+, etc) as a seed, then the game could take those characters and convert them into ASCII numerical values, with those numbers the seed would be automatically formed, which the generator would use to create the world.

**Comment by lino-levan** [comment]
While looking at the seed code, I realized that it is seriously bugged. If the user types the seed "99999999999999999999", the game will crash while trying to load the world due to it being larger than the floating point limit of "9223372036854775807". 

In conclusion, I have written the code and will be doing a pull request for an update that does the following:
- Allows for seeds with alphabetic characters
- Hopefully prevents crashes by using the java hashCode method + some magic

This will not impact previously generated worlds because they don't rely on the world gen menu.

**Comment by lino-levan** [comment]
@Makkkkus I think this should be closed?
